version: '3.9'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: handin_dev
      POSTGRES_USER: postgres # Replace 'myapp_user' with your desired username
      POSTGRES_PASSWORD: postgres # Replace 'myapp_password' with your desired password
    volumes:
      - handin-db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432" # If you want to access the database externally, map the container port to a host port
volumes:
  handin-db-data: