version: '3.9'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/app
  # environment:
  #   DATABASE_URL: "ecto://postgres:postgres@db/handin_dev" # Template : "ecto://db_user:db_password@ip_or_compose_service_name/db_name"
  #   SECRET_KEY_BASE: bRFH7l4RrhEA+rN4iqORKE9IFRPC2r/JI3X1wf8QTSVa4ERm567EANaqEp8uasZ6 # Can literally be anything, but generally generated randomly by tools like mix phx.gen.secret
  db:
    image: postgres:14.1-alpine
    container_name: handin_database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=handin_dev
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
volumes:
  db:
